### PR TITLE
fix mantastic issue 1

### PR DESCRIPTION
**Pull request by lbdyck**
this code should fix the issue of no filter provided

### CODE REVIEW

**Review by netskink — APPROVED** [review]
fwiw, I will attempt to add my standard option hander compatible with bourne and bash shell today.


Can you list the options and params or point to where they are documented?


My code works on items like this:

* -foo
* -foo 2

everything else is considered just a param. ie


```
$ ./somescript.sh -opt1 -opt2 5 parm1 parm2
```

-opt1 would be considred a switch
-opt2 5 would be considered setting an optional switch to a value
parm1 and parm2 woujld be parms.

**Comment by netskink** [comment]
> The syntax is:
> 
> ```
> mantastic man-page x  x is any non-blank to display manpage
>     mantastic string      find string in manpage description and list
>    mantastic -help, -h   display this help
>     mantastic             prompt for string
> ```
> 
> hope this helps

can you provide a usage example for 'mantastic man-page x' please?

**Comment by lbdyck** [comment]
Samples:

`mantastic`     to be prompted
`mantastic git`   to be prompted with a list of all man pages with `git` in the man database description
`mantastic git x` to just view the `git` man page

the prompts for the 1st is to provide the word to search the database for

**Comment by lbdyck** [comment]
Merge completed

**Pull request merged**
